default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  min_messages: warning

development:
  <<: *default
  database: app_development
  username: root
  password: password

test:
  <<: *default
  database: app_test
  username: root
  password: password